### PR TITLE
Add Island Perimeter in Java - Oct 4

### PR DESCRIPTION
**Pull request by AlbusDracoSam**
Full program from Main class to output.

### CODE REVIEW

**Comment by AlbusDracoSam** [comment]
Hey! No hacktober accepted tag ?

**Comment by prateek19070** [comment]
> Hey! No hacktober accepted tag ?

"A pull request is considered approved once it has an overall approving review from maintainers, or has been merged by maintainers, or has been given the 'hacktoberfest-accepted' label."

Also added the hacktoberfest-accepted label for your reference.

**Comment by AlbusDracoSam** [comment]
So it's like automatic tagging? I'm a newbie bare with me.

**Comment by prateek19070** [comment]
The statement lists one of the options as "merged by the maintainers". So, once it is approved by the maintainers, there should not be a need of hacktoberfest-accepted label. However, for the safe side I have added the label to each of the pull requests, so that no one's pull request is disqualified.

**Comment by AlbusDracoSam** [comment]
Got it. Thanks a lot for the explanation! It means a lot

**Pull request merged**
